In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
%matplotlib inline
from sklearn.preprocessing import RobustScaler
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report,accuracy_score
from sklearn.neural_network import MLPClassifier

In [2]:
dataTrain = pd.read_csv("train.csv")
dataTrain

,time_left,ct_score,t_score,map,bomb_planted,ct_health,t_health,ct_armor,t_armor,ct_money,...,ct_grenade_smokegrenade,t_grenade_smokegrenade,ct_grenade_incendiarygrenade,t_grenade_incendiarygrenade,ct_grenade_molotovgrenade,t_grenade_molotovgrenade,ct_grenade_decoygrenade,t_grenade_decoygrenade,round_winner,id
0,175.00,5.0,10.0,de_nuke,False,500.0,500.0,100.0,0.0,3350.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0
1,175.00,0.0,0.0,de_inferno,False,500.0,500.0,400.0,100.0,700.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,1
2,166.95,6.0,1.0,de_dust2,False,500.0,500.0,0.0,190.0,33050.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0,2
3,85.34,9.0,6.0,de_nuke,False,479.0,465.0,300.0,492.0,550.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,3
4,74.95,10.0,4.0,de_inferno,False,419.0,300.0,485.0,300.0,4400.0,...,1.0,3.0,2.0,0.0,0.0,3.0,0.0,0.0,1,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85682,174.95,5.0,8.0,de_nuke,False,500.0,500.0,197.0,0.0,18400.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1,85682
85683,30.75,4.0,0.0,de_inferno,True,390.0,303.0,389.0,374.0,6600.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,85683
85684,74.95,4.0,3.0,de_nuke,False,500.0,400.0,500.0,367.0,300.0,...,2.0,3.0,1.0,0.0,0.0,4.0,1.0,0.0,1,85684
85685,114.91,0.0,0.0,de_mirage,False,500.0,500.0,300.0,400.0,500.0,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0,85685
85686,54.94,4.0,12.0,de_nuke,False,463.0,400.0,487.0,400.0,450.0,...,0.0,2.0,0.0,0.0,0.0,1.0,0.0,1.0,1,85686

In [3]:
dataTest = pd.read_csv("test.csv")
dataTest

,time_left,ct_score,t_score,map,bomb_planted,ct_health,t_health,ct_armor,t_armor,ct_money,...,t_grenade_flashbang,ct_grenade_smokegrenade,t_grenade_smokegrenade,ct_grenade_incendiarygrenade,t_grenade_incendiarygrenade,ct_grenade_molotovgrenade,t_grenade_molotovgrenade,ct_grenade_decoygrenade,t_grenade_decoygrenade,id
0,175.00,11.0,4.0,de_vertigo,False,500.0,500.0,400.0,300.0,700.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0
1,94.95,8.0,4.0,de_dust2,False,400.0,450.0,400.0,477.0,10300.0,...,2.0,2.0,2.0,3.0,0.0,0.0,0.0,0.0,0.0,1
2,14.93,14.0,10.0,de_dust2,False,366.0,100.0,395.0,98.0,2350.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,2
3,46.27,12.0,15.0,de_nuke,False,400.0,446.0,399.0,434.0,300.0,...,5.0,0.0,1.0,0.0,0.0,0.0,2.0,0.0,0.0,3
4,37.07,18.0,18.0,de_train,False,100.0,200.0,100.0,200.0,10100.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36718,175.00,6.0,9.0,de_mirage,False,500.0,500.0,0.0,0.0,4000.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,36718
36719,114.95,0.0,2.0,de_nuke,False,500.0,500.0,0.0,474.0,11800.0,...,4.0,0.0,3.0,0.0,0.0,0.0,2.0,0.0,0.0,36719
36720,39.45,8.0,1.0,de_nuke,True,200.0,293.0,173.0,366.0,150.0,...,2.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,36720
36721,175.00,11.0,4.0,de_overpass,False,500.0,500.0,400.0,100.0,600.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,36721
36722,114.96,3.0,8.0,de_dust2,False,500.0,500.0,500.0,434.0,5550.0,...,5.0,5.0,5.0,4.0,0.0,0.0,4.0,0.0,0.0,36722

In [4]:
col = dataTrain.columns
cols = dataTest.columns

In [5]:
# checking for columns for only one value
t=[]
for i in col:
    t.append(dataTrain[i].nunique())

In [6]:
temp =[]
for i in range(len(t)):
    if t[i]==1:
        temp.append(i)
        print(i)

22
30
36
37
52
58
60

In [7]:
dataTrain.drop([col[22], col[30],col[36], col[37], col[52], col[58], col[60]], axis = 1, inplace = True)
dataTest.drop([cols[22], cols[30],cols[36], cols[37], cols[52], cols[58], cols[60]], axis = 1, inplace = True) # dropping those columns
print(col[22])
print(col[30])
print(col[37])
print(col[52])
print(col[58])
print(col[60])

ct_weapon_bizon
ct_weapon_g3sg1
t_weapon_m249
ct_weapon_negev
ct_weapon_r8revolver
ct_weapon_sawedoff

In [8]:
label_encoder = preprocessing.LabelEncoder() 
dataTrain['map'] = label_encoder.fit_transform(dataTrain['map'])
dataTest['map'] = label_encoder.fit_transform(dataTest['map'])

In [9]:
dataTest['id']

0            0
1            1
2            2
3            3
4            4
         ...
36718    36718
36719    36719
36720    36720
36721    36721
36722    36722
Name: id, Length: 36723, dtype: int64

In [10]:
dataTrain['bomb_planted'] = label_encoder.fit_transform(dataTrain['bomb_planted'])
dataTest['bomb_planted'] = label_encoder.fit_transform(dataTest['bomb_planted'])

In [11]:
col = dataTrain.columns
cols = dataTest.columns

In [12]:
dataTrain

,time_left,ct_score,t_score,map,bomb_planted,ct_health,t_health,ct_armor,t_armor,ct_money,...,ct_grenade_smokegrenade,t_grenade_smokegrenade,ct_grenade_incendiarygrenade,t_grenade_incendiarygrenade,ct_grenade_molotovgrenade,t_grenade_molotovgrenade,ct_grenade_decoygrenade,t_grenade_decoygrenade,round_winner,id
0,175.00,5.0,10.0,4,0,500.0,500.0,100.0,0.0,3350.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0
1,175.00,0.0,0.0,2,0,500.0,500.0,400.0,100.0,700.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,1
2,166.95,6.0,1.0,1,0,500.0,500.0,0.0,190.0,33050.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0,2
3,85.34,9.0,6.0,4,0,479.0,465.0,300.0,492.0,550.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,3
4,74.95,10.0,4.0,2,0,419.0,300.0,485.0,300.0,4400.0,...,1.0,3.0,2.0,0.0,0.0,3.0,0.0,0.0,1,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85682,174.95,5.0,8.0,4,0,500.0,500.0,197.0,0.0,18400.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1,85682
85683,30.75,4.0,0.0,2,1,390.0,303.0,389.0,374.0,6600.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,85683
85684,74.95,4.0,3.0,4,0,500.0,400.0,500.0,367.0,300.0,...,2.0,3.0,1.0,0.0,0.0,4.0,1.0,0.0,1,85684
85685,114.91,0.0,0.0,3,0,500.0,500.0,300.0,400.0,500.0,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0,85685
85686,54.94,4.0,12.0,4,0,463.0,400.0,487.0,400.0,450.0,...,0.0,2.0,0.0,0.0,0.0,1.0,0.0,1.0,1,85686

In [13]:
c = []
for i in col:
    c.append(dataTrain['round_winner'].corr(dataTrain[i]))

In [14]:
dataTrain.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85687 entries, 0 to 85686
Data columns (total 91 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   time_left                     85687 non-null  float64
 1   ct_score                      85687 non-null  float64
 2   t_score                       85687 non-null  float64
 3   map                           85687 non-null  int32
 4   bomb_planted                  85687 non-null  int64
 5   ct_health                     85687 non-null  float64
 6   t_health                      85687 non-null  float64
 7   ct_armor                      85687 non-null  float64
 8   t_armor                       85687 non-null  float64
 9   ct_money                      85687 non-null  float64
 10  t_money                       85687 non-null  float64
 11  ct_helmets                    85687 non-null  float64
 12  t_helmets                     85687 non-null  float64
 13  ct_defuse_kits                85687 non-null  float64
 14  ct_players_alive              85687 non-null  float64
 15  t_players_alive               85687 non-null  float64
 16  ct_weapon_ak47                85687 non-null  float64
 17  t_weapon_ak47                 85687 non-null  float64
 18  ct_weapon_aug                 85687 non-null  float64
 19  t_weapon_aug                  85687 non-null  float64
 20  ct_weapon_awp                 85687 non-null  float64
 21  t_weapon_awp                  85687 non-null  float64
 22  t_weapon_bizon                85687 non-null  float64
 23  ct_weapon_cz75auto            85687 non-null  float64
 24  t_weapon_cz75auto             85687 non-null  float64
 25  ct_weapon_elite               85687 non-null  float64
 26  t_weapon_elite                85687 non-null  float64
 27  ct_weapon_famas               85687 non-null  float64
 28  t_weapon_famas                85687 non-null  float64
 29  t_weapon_g3sg1                85687 non-null  float64
 30  ct_weapon_galilar             85687 non-null  float64
 31  t_weapon_galilar              85687 non-null  float64
 32  ct_weapon_glock               85687 non-null  float64
 33  t_weapon_glock                85687 non-null  float64
 34  ct_weapon_m4a1s               85687 non-null  float64
 35  t_weapon_m4a1s                85687 non-null  float64
 36  ct_weapon_m4a4                85687 non-null  float64
 37  t_weapon_m4a4                 85687 non-null  float64
 38  ct_weapon_mac10               85687 non-null  float64
 39  t_weapon_mac10                85687 non-null  float64
 40  ct_weapon_mag7                85687 non-null  float64
 41  t_weapon_mag7                 85687 non-null  float64
 42  ct_weapon_mp5sd               85687 non-null  float64
 43  t_weapon_mp5sd                85687 non-null  float64
 44  ct_weapon_mp7                 85687 non-null  float64
 45  t_weapon_mp7                  85687 non-null  float64
 46  ct_weapon_mp9                 85687 non-null  float64
 47  t_weapon_mp9                  85687 non-null  float64
 48  t_weapon_negev                85687 non-null  float64
 49  ct_weapon_nova                85687 non-null  float64
 50  t_weapon_nova                 85687 non-null  float64
 51  ct_weapon_p90                 85687 non-null  float64
 52  t_weapon_p90                  85687 non-null  float64
 53  t_weapon_r8revolver           85687 non-null  float64
 54  t_weapon_sawedoff             85687 non-null  float64
 55  ct_weapon_scar20              85687 non-null  float64
 56  t_weapon_scar20               85687 non-null  float64
 57  ct_weapon_sg553               85687 non-null  float64
 58  t_weapon_sg553                85687 non-null  float64
 59  ct_weapon_ssg08               85687 non-null  float64
 60  t_weapon_ssg08                85687 non-null  float64
 61  ct_weapon_ump45               85687 non-null  float64
 62  t_weapon_ump45                85687 non-null  float64
 63  ct_weapon_xm1014              85687 non-null  float64
 64  t_weapon_xm1014               85687 non-null  float64
 65  ct_weapon_deagle              85687 non-null  float64
 66  t_weapon_deagle               85687 non-null  float64
 67  ct_weapon_fiveseven           85687 non-null  float64
 68  t_weapon_fiveseven            85687 non-null  float64
 69  ct_weapon_usps                85687 non-null  float64
 70  t_weapon_usps                 85687 non-null  float64
 71  ct_weapon_p250                85687 non-null  float64
 72  t_weapon_p250                 85687 non-null  float64
 73  ct_weapon_p2000               85687 non-null  float64
 74  t_weapon_p2000                85687 non-null  float64
 75  ct_weapon_tec9                85687 non-null  float64
 76  t_weapon_tec9                 85687 non-null  float64
 77  ct_grenade_hegrenade          85687 non-null  float64
 78  t_grenade_hegrenade           85687 non-null  float64
 79  ct_grenade_flashbang          85687 non-null  float64
 80  t_grenade_flashbang           85687 non-null  float64
 81  ct_grenade_smokegrenade       85687 non-null  float64
 82  t_grenade_smokegrenade        85687 non-null  float64
 83  ct_grenade_incendiarygrenade  85687 non-null  float64
 84  t_grenade_incendiarygrenade   85687 non-null  float64
 85  ct_grenade_molotovgrenade     85687 non-null  float64
 86  t_grenade_molotovgrenade      85687 non-null  float64
 87  ct_grenade_decoygrenade       85687 non-null  float64
 88  t_grenade_decoygrenade        85687 non-null  float64
 89  round_winner                  85687 non-null  int64
 90  id                            85687 non-null  int64
dtypes: float64(87), int32(1), int64(3)
memory usage: 59.2 MB

In [15]:
id = dataTest[['id']]
id

In [16]:
scl = RobustScaler()

In [17]:
dataTrain=scl.fit_transform(dataTrain)
dataTest=scl.fit_transform(dataTest)

In [18]:
dataTrain = pd.DataFrame(dataTrain, columns = col)
dataTrain

,time_left,ct_score,t_score,map,bomb_planted,ct_health,t_health,ct_armor,t_armor,ct_money,...,ct_grenade_smokegrenade,t_grenade_smokegrenade,ct_grenade_incendiarygrenade,t_grenade_incendiarygrenade,ct_grenade_molotovgrenade,t_grenade_molotovgrenade,ct_grenade_decoygrenade,t_grenade_decoygrenade,round_winner,id
0,0.715089,-0.142857,0.571429,0.333333,0.0,0.000000,0.000000,-0.948630,-1.132653,-0.161654,...,-0.333333,-0.333333,0.0,0.0,0.0,-0.5,0.0,0.0,0.0,-1.000000
1,0.715089,-0.857143,-0.857143,-0.333333,0.0,0.000000,0.000000,0.078767,-0.792517,-0.360902,...,-0.333333,-0.333333,0.0,0.0,0.0,-0.5,0.0,0.0,1.0,-0.999977
2,0.643214,0.000000,-0.714286,-0.666667,0.0,0.000000,0.000000,-1.291096,-0.486395,2.071429,...,-0.333333,0.000000,0.0,0.0,0.0,-0.5,0.0,0.0,0.0,-0.999953
3,-0.085446,0.428571,0.000000,0.333333,0.0,-0.140940,-0.195531,-0.263699,0.540816,-0.372180,...,-0.333333,-0.333333,0.0,0.0,0.0,-0.5,0.0,0.0,1.0,-0.999930
4,-0.178214,0.571429,-0.285714,-0.333333,0.0,-0.543624,-1.117318,0.369863,-0.112245,-0.082707,...,0.000000,0.666667,1.0,0.0,0.0,1.0,0.0,0.0,1.0,-0.999907
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85682,0.714643,-0.142857,0.285714,0.333333,0.0,0.000000,0.000000,-0.616438,-1.132653,0.969925,...,-0.333333,-0.333333,0.5,0.0,0.0,-0.5,0.0,0.0,1.0,0.999907
85683,-0.572857,-0.285714,-0.857143,-0.333333,1.0,-0.738255,-1.100559,0.041096,0.139456,0.082707,...,0.000000,-0.333333,0.0,0.0,0.0,-0.5,0.0,0.0,1.0,0.999930
85684,-0.178214,-0.285714,-0.428571,0.333333,0.0,0.000000,-0.558659,0.421233,0.115646,-0.390977,...,0.333333,0.666667,0.5,0.0,0.0,1.5,1.0,0.0,1.0,0.999953
85685,0.178571,-0.857143,-0.857143,0.000000,0.0,0.000000,0.000000,-0.263699,0.227891,-0.375940,...,0.000000,0.000000,0.0,0.0,0.0,-0.5,0.0,0.0,0.0,0.999977
85686,-0.356875,-0.285714,0.857143,0.333333,0.0,-0.248322,-0.558659,0.376712,0.227891,-0.379699,...,-0.333333,0.333333,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.000000

In [19]:
dataTest

array([[ 7.15089286e-01,  7.14285714e-01, -2.85714286e-01, ...,
         0.00000000e+00,  1.00000000e+00, -1.00000000e+00],
       [ 3.57142857e-04,  2.85714286e-01, -2.85714286e-01, ...,
         0.00000000e+00,  0.00000000e+00, -9.99945537e-01],
       [-7.14107143e-01,  1.14285714e+00,  5.71428571e-01, ...,
         0.00000000e+00,  0.00000000e+00, -9.99891073e-01],
       ...,
       [-4.95178571e-01,  2.85714286e-01, -7.14285714e-01, ...,
         0.00000000e+00,  0.00000000e+00,  9.99891073e-01],
       [ 7.15089286e-01,  7.14285714e-01, -2.85714286e-01, ...,
         0.00000000e+00,  0.00000000e+00,  9.99945537e-01],
       [ 1.79017857e-01, -4.28571429e-01,  2.85714286e-01, ...,
         0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

In [20]:
dataTest = pd.DataFrame(dataTest, columns = cols)

In [21]:
dataTest['id']

0       -1.000000
1       -0.999946
2       -0.999891
3       -0.999837
4       -0.999782
           ...
36718    0.999782
36719    0.999837
36720    0.999891
36721    0.999946
36722    1.000000
Name: id, Length: 36723, dtype: float64

In [22]:
dataTrain['round_winner'] = label_encoder.fit_transform(dataTrain['round_winner'])

In [23]:
y_train = dataTrain['round_winner']
X_train = dataTrain.drop('round_winner', axis=1)
X_test = dataTest

In [24]:
x_train, x_test, y_train1, y_test = train_test_split(X_train, y_train, test_size = 0.2, random_state = 42)

In [25]:
model = RandomForestClassifier()
model.fit(X_train,y_train)
predictions = model.predict(X_test)

In [26]:
model_3 = RandomForestClassifier()
model_3.fit(x_train,y_train1)
pred_3 = model_3.predict(x_test)
cr3 = classification_report(y_test,pred_3)
print(cr3)

              precision    recall  f1-score   support

           0       0.86      0.85      0.85      8709
           1       0.85      0.86      0.85      8429

    accuracy                           0.85     17138
   macro avg       0.85      0.85      0.85     17138
weighted avg       0.85      0.85      0.85     17138

In [27]:
predictions

array([1, 0, 1, ..., 0, 1, 0], dtype=int64)

In [28]:
submission = id
submission

          id
0          0
1          1
2          2
3          3
4          4
...      ...
36718  36718
36719  36719
36720  36720
36721  36721
36722  36722

[36723 rows x 1 columns]

In [29]:
submission['round_winner'] = predictions
submission

C:\Users\MARIAA~1\AppData\Local\Temp/ipykernel_1160/245844295.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  submission['round_winner'] = predictions

          id  round_winner
0          0             1
1          1             0
2          2             1
3          3             0
4          4             0
...      ...           ...
36718  36718             1
36719  36719             0
36720  36720             0
36721  36721             1
36722  36722             0

[36723 rows x 2 columns]

In [30]:
submission.to_csv('submission_RandomForest.csv', index = None)